### ISSUE TITLE
getSDF

### ISSUE THREAD

**Issue by PWhiddy** [bnanner/sculpture-park-core#33]
opposite of applySDF
(should applySDF be renamed setSDF?)

**Comment by torinmb** [comment]
Yeah I think setSDF since we have setSpace

**Comment by torinmb** [comment]
is getSDF just the same as surfaceDistance?

**Comment by PWhiddy** [comment]
> Yeah I think setSDF since we have setSpace

We'll need to update our existing shaders for this change

> is getSDF just the same as surfaceDistance?

No, this is for getting the current SDF at that moment in the current shape. So it would be the same if you do it as the very last line of the script, but this allows you to capture/modify the value in the middle of the construction
