### ISSUE TITLE
Create repo for ultra lightweight render page

### ISSUE THREAD

**Issue by PWhiddy** [bnanner/sculpture-park-core#34]

**Comment by torinmb** [comment]
Seems like this could be a good fit
https://github.com/patriciogonzalezvivo/glslCanvas

**Comment by torinmb** [comment]
Looks like library is only 17.2 KB
![image](https://user-images.githubusercontent.com/6014011/70206874-ed773580-16f6-11ea-93f1-b344ebb9b7ab.png)

**Comment by PWhiddy** [comment]
The gray number is the actual size of the file. The minified version of that lib is 27kb.

Not sure why we would want to use any library here??

Here's a working example of everything we need. Just add our generated glsl to the fragment, add a render loop which updates a time/mouse uniform. No libraries, _including html_ , whole thing is 2kb before adding generated glsl.

<!doctype html>
<html>
   <body>
      <canvas width = "570" height = "570" id = "my_Canvas"></canvas>
      <script>
         var canvas = document.getElementById('my_Canvas');
         gl = canvas.getContext('experimental-webgl');
         var vertices = [
            -0.5,0.5,0.0,
            -0.5,-0.5,0.0,
            0.5,-0.5,0.0,
            0.5,0.5,0.0 
         ];
         indices = [3,2,1,3,1,0];
         var vertex_buffer = gl.createBuffer();
         gl.bindBuffer(gl.ARRAY_BUFFER, vertex_buffer);
         gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(vertices), gl.STATIC_DRAW);
         gl.bindBuffer(gl.ARRAY_BUFFER, null);
         var Index_Buffer = gl.createBuffer();
         gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, Index_Buffer);
         gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, new Uint16Array(indices), gl.STATIC_DRAW);
         gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, null);
         var vertCode =
            'attribute vec3 coordinates;' +
            'void main(void) {' +
               ' gl_Position = vec4(coordinates, 1.0);' +
            '}';
         var vertShader = gl.createShader(gl.VERTEX_SHADER);
         gl.shaderSource(vertShader, vertCode);
         gl.compileShader(vertShader);
         var fragCode =
            'void main(void) {' +
               ' gl_FragColor = vec4(0.0, 0.0, 0.0, 0.1);' +
            '}';
         var fragShader = gl.createShader(gl.FRAGMENT_SHADER);
         gl.shaderSource(fragShader, fragCode);
         gl.compileShader(fragShader);
         var shaderProgram = gl.createProgram();
         gl.attachShader(shaderProgram, vertShader);
         gl.attachShader(shaderProgram, fragShader);
         gl.linkProgram(shaderProgram);
         gl.useProgram(shaderProgram);
         gl.bindBuffer(gl.ARRAY_BUFFER, vertex_buffer);
         gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, Index_Buffer); 
         var coord = gl.getAttribLocation(shaderProgram, "coordinates");
         gl.vertexAttribPointer(coord, 3, gl.FLOAT, false, 0, 0);
         gl.enableVertexAttribArray(coord);
         gl.clearColor(0.5, 0.5, 0.5, 0.9);
         gl.enable(gl.DEPTH_TEST);
         gl.clear(gl.COLOR_BUFFER_BIT);
         gl.viewport(0,0,canvas.width,canvas.height);
         gl.drawElements(gl.TRIANGLES, indices.length, gl.UNSIGNED_SHORT,0);
      </script>
   </body>
</html>

**Comment by PWhiddy** [comment]
Here's it running, rendering a box with the placeholder shader

<img width="730" alt="Screen Shot 2019-12-04 at 10 11 09 PM" src="https://user-images.githubusercontent.com/15711120/70208667-0d046300-16e3-11ea-88fc-60394ceb87f4.png">

**Comment by PWhiddy** [comment]
source:
https://www.tutorialspoint.com/webgl/webgl_drawing_a_quad.htm
